// gameModel.ts

// Interface para os dados do Pokémon
export interface Pokemon {
    id: number;
    nome: string;
    imagem: string; // URL da imagem
}

// Interface para uma carta individual (usada no deck)
export interface Card {
    id: string; // UUID único da carta
    pokemon: string; // Nome do Pokémon
    imagem: string; // URL da imagem (CRÍTICO)
    flipped: boolean;
    matched: boolean;
}

// Interface para o estado completo do jogo
export interface Game {
    id: string; 
    cards: Card[];
    moves: number;
}

// Lista EXPANDIDA de Pokémons de Kanto (Geração 1)
// Usamos a URL padrão da PokeAPI para as imagens (sprites)
export let pokemons: Pokemon[] = [
    { id: 1, nome: "Bulbasaur", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png" },
    { id: 2, nome: "Ivysaur", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png" },
    { id: 3, nome: "Venusaur", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png" },
    { id: 4, nome: "Charmander", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png" },
    { id: 5, nome: "Charmeleon", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png" },
    { id: 6, nome: "Charizard", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png" },
    { id: 7, nome: "Squirtle", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png" },
    { id: 8, nome: "Wartortle", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png" },
    { id: 9, nome: "Blastoise", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png" },
    { id: 10, nome: "Caterpie", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png" },
    { id: 11, nome: "Metapod", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png" },
    { id: 12, nome: "Butterfree", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png" },
    { id: 13, nome: "Weedle", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png" },
    { id: 14, nome: "Kakuna", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png" },
    { id: 15, nome: "Beedrill", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png" },
    { id: 16, nome: "Pidgey", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png" },
    { id: 17, nome: "Pidgeotto", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png" },
    { id: 18, nome: "Pidgeot", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png" },
    { id: 19, nome: "Rattata", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png" },
    { id: 20, nome: "Raticate", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png" },
    { id: 21, nome: "Spearow", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png" },
    { id: 22, nome: "Fearow", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png" },
    { id: 23, nome: "Ekans", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png" },
    { id: 24, nome: "Arbok", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png" },
    { id: 25, nome: "Pikachu", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png" },
    { id: 26, nome: "Raichu", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png" },
    { id: 27, nome: "Sandshrew", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png" },
    { id: 28, nome: "Sandslash", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png" },
    { id: 29, nome: "Nidoran♀", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png" },
    { id: 30, nome: "Nidorina", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png" },
    { id: 31, nome: "Nidoqueen", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png" },
    { id: 32, nome: "Nidoran♂", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png" },
    { id: 33, nome: "Nidorino", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png" },
    { id: 34, nome: "Nidoking", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png" },
    { id: 35, nome: "Clefairy", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png" },
    { id: 36, nome: "Clefable", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png" },
    { id: 37, nome: "Vulpix", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png" },
    { id: 38, nome: "Ninetales", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png" },
    { id: 39, nome: "Jigglypuff", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png" },
    { id: 40, nome: "Wigglytuff", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png" },
    { id: 41, nome: "Zubat", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png" },
    { id: 42, nome: "Golbat", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png" },
    { id: 43, nome: "Oddish", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png" },
    { id: 44, nome: "Gloom", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png" },
    { id: 45, nome: "Vileplume", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png" },
    { id: 46, nome: "Paras", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png" },
    { id: 47, nome: "Parasect", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png" },
    { id: 48, nome: "Venonat", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png" },
    { id: 49, nome: "Venomoth", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png" },
    { id: 50, nome: "Diglett", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png" },
    { id: 51, nome: "Dugtrio", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png" },
    { id: 52, nome: "Meowth", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png" },
    { id: 53, nome: "Persian", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png" },
    { id: 54, nome: "Psyduck", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png" },
    { id: 55, nome: "Golduck", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png" },
    { id: 56, nome: "Mankey", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png" },
    { id: 57, nome: "Primeape", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png" },
    { id: 58, nome: "Growlithe", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png" },
    { id: 59, nome: "Arcanine", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png" },
    { id: 60, nome: "Poliwag", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png" },
    { id: 61, nome: "Poliwhirl", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png" },
    { id: 62, nome: "Poliwrath", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png" },
    { id: 63, nome: "Abra", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png" },
    { id: 64, nome: "Kadabra", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png" },
    { id: 65, nome: "Alakazam", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png" },
    { id: 66, nome: "Machop", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png" },
    { id: 67, nome: "Machoke", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png" },
    { id: 68, nome: "Machamp", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png" },
    { id: 69, nome: "Bellsprout", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png" },
    { id: 70, nome: "Weepinbell", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png" },
    { id: 71, nome: "Victreebel", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png" },
    { id: 72, nome: "Tentacool", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png" },
    { id: 73, nome: "Tentacruel", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png" },
    { id: 74, nome: "Geodude", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png" },
    { id: 75, nome: "Graveler", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png" },
    { id: 76, nome: "Golem", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png" },
    { id: 77, nome: "Ponyta", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png" },
    { id: 78, nome: "Rapidash", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png" },
    { id: 79, nome: "Slowpoke", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png" },
    { id: 80, nome: "Slowbro", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png" },
    { id: 81, nome: "Magnemite", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png" },
    { id: 82, nome: "Magneton", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png" },
    { id: 83, nome: "Farfetch'd", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png" },
    { id: 84, nome: "Doduo", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png" },
    { id: 85, nome: "Dodrio", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png" },
    { id: 86, nome: "Seel", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png" },
    { id: 87, nome: "Dewgong", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png" },
    { id: 88, nome: "Grimer", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png" },
    { id: 89, nome: "Muk", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png" },
    { id: 90, nome: "Shellder", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png" },
    { id: 91, nome: "Cloyster", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png" },
    { id: 92, nome: "Gastly", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png" },
    { id: 93, nome: "Haunter", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png" },
    { id: 94, nome: "Gengar", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png" },
    { id: 95, nome: "Onix", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png" },
    { id: 96, nome: "Drowzee", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png" },
    { id: 97, nome: "Hypno", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png" },
    { id: 98, nome: "Krabby", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png" },
    { id: 99, nome: "Kingler", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png" },
    { id: 100, nome: "Voltorb", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png" },
    { id: 101, nome: "Electrode", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png" },
    { id: 102, nome: "Exeggcute", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png" },
    { id: 103, nome: "Exeggutor", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png" },
    { id: 104, nome: "Cubone", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png" },
    { id: 105, nome: "Marowak", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png" },
    { id: 106, nome: "Hitmonlee", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png" },
    { id: 107, nome: "Hitmonchan", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png" },
    { id: 108, nome: "Lickitung", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png" },
    { id: 109, nome: "Koffing", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png" },
    { id: 110, nome: "Weezing", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png" },
    { id: 111, nome: "Rhyhorn", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png" },
    { id: 112, nome: "Rhydon", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png" },
    { id: 113, nome: "Chansey", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png" },
    { id: 114, nome: "Tangela", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png" },
    { id: 115, nome: "Kangaskhan", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png" },
    { id: 116, nome: "Horsea", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png" },
    { id: 117, nome: "Seadra", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png" },
    { id: 118, nome: "Goldeen", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png" },
    { id: 119, nome: "Seaking", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png" },
    { id: 120, nome: "Staryu", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png" },
    { id: 121, nome: "Starmie", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png" },
    { id: 122, nome: "Mr. Mime", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png" },
    { id: 123, nome: "Scyther", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png" },
    { id: 124, nome: "Jynx", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png" },
    { id: 125, nome: "Electabuzz", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png" },
    { id: 126, nome: "Magmar", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png" },
    { id: 127, nome: "Pinsir", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png" },
    { id: 128, nome: "Tauros", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png" },
    { id: 129, nome: "Magikarp", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png" },
    { id: 130, nome: "Gyarados", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png" },
    { id: 131, nome: "Lapras", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png" },
    { id: 132, nome: "Ditto", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png" },
    { id: 133, nome: "Eevee", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png" },
    { id: 134, nome: "Vaporeon", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png" },
    { id: 135, nome: "Jolteon", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png" },
    { id: 136, nome: "Flareon", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png" },
    { id: 137, nome: "Porygon", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png" },
    { id: 138, nome: "Omanyte", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png" },
    { id: 139, nome: "Omastar", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png" },
    { id: 140, nome: "Kabuto", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png" },
    { id: 141, nome: "Kabutops", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png" },
    { id: 142, nome: "Aerodactyl", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png" },
    { id: 143, nome: "Snorlax", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png" },
    { id: 144, nome: "Articuno", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png" },
    { id: 145, nome: "Zapdos", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png" },
    { id: 146, nome: "Moltres", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png" },
    { id: 147, nome: "Dratini", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png" },
    { id: 148, nome: "Dragonair", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png" },
    { id: 149, nome: "Dragonite", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png" },
    { id: 150, nome: "Mewtwo", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png" },
    { id: 151, nome: "Mew", imagem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png" },
];
